# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build - Apk

on:
  push:
    branches:
      - maiin
  pull_request:
    branches:
      - maiin

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.32.5
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --split-per-abi
        working-directory: qr_code_preview


